version: "3"
services:
  # Bitcoin core
  bitcoin:
    container_name: bitcoin
    image: tiero/bitcoin-core
    networks:
      local:
        ipv4_address: 10.10.0.10
    volumes:
      - ${BITCOIN_VOLUME}:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
      - 8333:8333
    command:
      -printtoconsole
      -server=1
      -daemon=0
      -txindex=1
      -disablewallet=1
      -rpcuser=${BITCOIN_RPC_USER}
      -rpcpassword=${BITCOIN_RPC_PASSWORD}
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -maxorphantx=10
      -maxmempool=50
      -maxconnections=40
      -maxuploadtarget=5000
  electrs:
    container_name: electrs
    image: vulpemventures/electrs:latest
    networks:
      local:
        ipv4_address: 10.10.0.11
    depends_on:
      - bitcoin
    volumes:
      - ${ELECTRS_VOLUME}:/db
    ports:
      - 3000:3000
      - 50001:50001
    command:
      - -vvvv
      - --index-batch-size
      - "10"
      - --db-dir
      - /db
      - --daemon-rpc-addr
      - 10.10.0.10:8332
      - --cookie
      - ${BITCOIN_RPC_USER}:${BITCOIN_RPC_PASSWORD}
      - --http-addr
      - 0.0.0.0:3000
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
